### ISSUE TITLE
Python 3 problems

### ISSUE THREAD

**Issue by alyoshak19** [ruediger/Boost-Pretty-Printer#12]
I converted printers.py using 
```
$ 2to3 -w printers.py
```
And now I get:
```
Python Exception <class 'TypeError'> object.__init__() takes no parameters: 
```
 all over the place. Any ideas?

**Comment by mateidavid** [comment]
The issue was that `int` and `long` are different in Py2, but only `int` exists in Py3. Removing the suffix was not necessarily ok. I fixed this in the latest pull request.

**Comment by zaufi** [comment]
@mateidavid: great work! looking forward when it'll be merged...

**Comment by bearlin** [comment]
Have the same ~1L issue, use @mateidavid 's branch fix this problem.
