### ISSUE TITLE
Should not format ptime using current time zone

### ISSUE THREAD

**Issue by mheiskan** [ruediger/Boost-Pretty-Printer#25]
I believe ptime should be formatted using the utcfromtimestamp method instead of fromtimestamp.
Consider this example:

`#include <iostream>`
`#include <boost/date_time.hpp>`
`int main() {`
`auto t = boost::posix_time::second_clock::local_time();`
`std::cout << t << std::endl;`
`}`

The program will print the current local time. However, if you debug the program, the current time zone is applied again, and depending on your timezone using `print t` in gdb will print something different.
Plain ptime objects have no attached time zone, and I applying one on them while debugging can lead to confusing results.

**Comment by mbalabin** [comment]
The issue was fixed in current master. Ptime printer now assumes that the stored time is UTC.
