### ISSUE TITLE
remove L in literal long

### ISSUE THREAD

**Issue by yuvalif** [ruediger/Boost-Pretty-Printer#27]
`File "<string>", line 3, in <module>
 File "/home/yuval/dev/Boost-Pretty-Printer/boost/printers.py", line 1223
    return long(str(parse_and_eval('*((void**)' + str(node_ptr) + ')')), 16) & (~1L)
SyntaxError: invalid syntax
`
got the above error (running Python 2.7.6 on ubuntu).
problem was fixed by removing the "L":

    return long(str(parse_and_eval('*((void**)' + str(node_ptr) + ')')), 16) & (~1)

**Comment by mateidavid** [comment]
Fixed in https://github.com/ruediger/Boost-Pretty-Printer/pull/23.
