### ISSUE TITLE
Printing std::array raises python exception when boost pretty printers are installed

### ISSUE THREAD

**Issue by huili80** [ruediger/Boost-Pretty-Printer#33]
Gdb complains about invalid cast for some reason.
This also messes up pretty printing std::array.
These errors go away if the boost printers are removed.

**Comment by mbalabin** [comment]
Please supply a complete gdb output (with boost version, gdb version and python version). Can you make an example program to reproduce the issue?

**Comment by huili80** [comment]
See the example code, and gdb output below.
Looks like the issue is just with std::array, including the its member c-array _M_elems. 
Standalone c-array appears to be okay.
boost version is 1.59.0, gdb is 7.9.1, gcc 4.8.5. OS is sles12sp1.

    1       #include <array>
    2
    3       int main()
    4       {
    5          int x = 0;
    6          bool a[3]{};
    7          std::array<bool,3>  ab{};
  > 8          int y = 9;
    9       }
 
(gdb) start
Temporary breakpoint 1, main () at tt.cpp:5
Missing separate debuginfos, use: zypper install libgcc_s1-debuginfo-5.2.1+r226025-4.1.x86_64 libstdc++6-debuginfo-5.2.1+r226025-4.1.x86_64
(gdb) p a
$1 = {false, false, false}
(gdb) p ab
$2 = {
  _M_elems = Python Exception <class 'gdb.error'> Invalid cast.:
{false, false, false}
}
(gdb) p ab._M_elems
$3 = Python Exception <class 'gdb.error'> Invalid cast.:
Python Exception <class 'gdb.error'> Invalid cast.:
{false, false, false}

**Comment by mbalabin** [comment]
Thanks, I can reproduce it on my system.

**Comment by mbalabin** [comment]
@huili80 You can try out this branch https://github.com/ruediger/Boost-Pretty-Printer/tree/issue33

**Comment by huili80** [comment]
Yes, that fixed the issue. Thank you!

**Comment by mbalabin** [comment]
[Fixed in master](https://github.com/ruediger/Boost-Pretty-Printer/commit/0dddbaac633fc2038a3a09e29f08d8ae91ef40c5)
