### ISSUE TITLE
BoostVariant printer doesn't split template argument types correctly when they're themselves templates with more than one template arguments

### ISSUE THREAD

**Issue by huili80** [ruediger/Boost-Pretty-Printer#34]
class BoostVariant tries to figure out the list of template argument types by using a regex, which doesn't work correctly when the types are themselves template instantiations with more than one template arguments.

Without using more complicated parsing tools, the following function should work correctly (at least in the several cases i tried) by simply matching angle brackets and splitting by commas, assuming the input typename is a string of comma-separated, well-formed, c++ typenames:
```
def split_variant_types(typename):
    unmatched = 0
    length = len(typename)
    b = e = 0
    while e < length:
        c = typename[e]
        if c == ',' and unmatched == 0:
            yield typename[b:e].strip()
            b = e = e + 1
        elif c == '<':
            unmatched += 1
        elif c == '>':
            unmatched -= 1
        e += 1
    yield typename[b:e].strip()
```

**Comment by mbalabin** [comment]
Ah, that regex. Thanks for spotting the problem. Fixing should be easy enough.

**Comment by huili80** [comment]
I found another problem while trying to making BoostVariant printer work for me. So it turns out the way it looks up the template argument types doesn't work for types that are qualified or are pointers/references.

For example, types as simple as ```boost::variant<int*, double const*>``` wouldn't work, because ```gdb.lookup_type('int*')``` and ```gdb.lookup_type('double const*')``` would raise ```gdb.error``` exceptions.

I think I found a workaround, by stripping the qualifications and pointer/references off of the types in order to be able to look up the type, then put the qualifications and pointer/references back to reconstruct the right type to cast to.

I attached the changes I made in the attachment. It worked for the cases I've encountered. Hopefully future release of gdb would allow looking up variadic template arguments like those in ```boost::variant```.

[BoostVariantFix.txt](https://github.com/ruediger/Boost-Pretty-Printer/files/1693106/BoostVariantFix.txt)

**Comment by mbalabin** [comment]
Feel free to make a pull request.

**Comment by mbalabin** [comment]
FYI: I tried gdb 7.12 and 8.0.1 and gdb.lookup_type still has the same issue: if variadic template arguments are preceded by fixed arguments, they can not be extracted. So, a workaround is still necessary.

**Comment by huili80** [comment]
Interesting.
I did make a pull request, let me know what you think and if anything needs to be changed.
I feel like the helper functions probably could be moved to utils.py, and have better names. Maybe something like ```split_parameter_pack```, ```strip_qualifiers_and_references``` and ```apply_qualifiers_and_references``` (too long?). What do you think?

**Comment by mbalabin** [comment]
Hi, I looked at your code. Two general remarks:
* You need to make a pull request from your branch to ruediger/Boost-Pretty-Printer:master (not to your fork's master). And turn on *Allow edits from maintainers* to make things easier.
* The code should be covered with unit tests. See `tests/testsuite.py` and `tests/testsuite.cpp`.
As for details:
* Better function names are a good idea. Strictly speaking, it should be `strip_qualifiers_and_references_and_pointers` but it is ridiculously long. Maybe just `strip_qualifiers`?
* Do not forget to supply a docstring for each function.
* I think that it is better to move variant printer and all its utility functions to a separate file (variant.py?), rather than moving to utils.py.

**Comment by mbalabin** [comment]
One more thing. Your implementation of strip_qps is too complex. I simplified it a bit:
```python
def strip_qps(typename):
  qps = []

  try:
    while True:
      typename = typename.rstrip()
      qual = next(q for q in ['&', '*', 'const', 'volatile'] if typename.endswith(q))
      typename = typename[:-len(qual)]
      qps.append(qual)
  except StopIteration:
    pass

  try:
    while True:
      typename = typename.lstrip()
      qual = next(q for q in ['const', 'volatile'] if typename.startswith(q))
      typename = typename[len(qual):]
      qps.append(qual)
  except StopIteration:
    pass

  return typename, qps[::-1]
```

**Comment by huili80** [comment]
Thanks for the simplified code! Let me try to change my forked version and add unit tests there first, before I tried to merge it back to ruediger/Boost-Pretty-Printer:master. I'm new to contributing on githut, in fact my fork was created by accident when i was trying to make a pull request.
